package com.gadgetseva.entity;

public enum ClaimStatus {
    CLAIM_SUBMITTED,
    APPROVAL_PENDING,
    APPROVED,
    REJECTED,
    REUPLOAD_PENDING,
    INVOICE_SUBMITTED,
    INVOICE_APPROVED,
    INVOICE_REJECTED,
    INVOICE_REUPLOAD_PENDING,
    READY_FOR_INSURANCE,
    SUBMITTED_TO_INSURANCE,
    CLOSED
}
