package com.gadgetseva.entity;

public enum RequestStatus {
    REQUEST_CREATED,
    PICKUP_ASSIGNED,
    PICKUP_IN_PROGRESS,
    CUSTOMER_NOT_AVAILABLE,
    CUSTOMER_RESCHEDULED,
    CUSTOMER_NOT_CONTACTABLE,
    PICKUP_COMPLETED,
    RECEIVED_AT_HUB,
    DIAGNOSIS_IN_PROGRESS,
    ESTIMATE_PREPARED,
    CASHLESS_PENDING_APPROVAL,
    CASHLESS_REVISION_REQUIRED,
    CASHLESS_REJECTED,
    CASHLESS_APPROVED,
    ESTIMATE_APPROVED,
    REPAIR_IN_PROGRESS,
    REPAIR_COMPLETED,
    TOTAL_LOSS,
    READY_FOR_DISPATCH,
    DELIVERY_ASSIGNED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    INVOICED,
    CLOSED
}
