import type { ServiceRequest } from '../types/models';

export const mockRequests: ServiceRequest[] = [
  {
    id: 1,
    requestNumber: 'GSH-20260323-1001',
    tenantCode: 'GSH-CORE',
    tenantName: 'Gadget Seva Hub Direct',
    loanNumber: 'LN-883712',
    certificateOfInsuranceNumber: 'COI-DEL-1129',
    previousTicketNumber: null,
    partnerReference: 'AMZ-RMA-4482',
    projectName: 'FG - Mobile All Risk IDFC',
    branchName: 'Indiranagar Branch',
    employeeCode: 'EMP-001',
    employeeName: 'Sonal Mehta',
    customerName: 'Nisha Verma',
    contactPerson: 'Nisha Verma',
    customerPhone: '0501001001',
    alternatePhone: '0501001009',
    whatsappNumber: '0501001001',
    customerGstin: '29ABCDE1234F1Z5',
    customerEmail: 'nisha@example.com',
    secondaryEmail: 'nisha.work@example.com',
    customerAddress: '12 MG Road, Stage 2',
    landmark: 'Near Metro Pillar 42',
    googleMapLink: 'https://maps.google.com/?q=12+MG+Road+Bengaluru',
    customerCity: 'Bengaluru',
    customerState: 'Karnataka',
    customerPostalCode: '560038',
    deviceLabel: 'Apple iPhone 14',
    deviceCategory: 'MOBILE',
    serialNumber: 'APL-IP14-23-001',
    imeiNumber: '490154203237518',
    imeiValidationStatus: 'VALID',
    qrCodePayload: 'IMEI:490154203237518;MODEL:IPHONE14',
    issueSummary: 'Screen cracked and touch lagging',
    issueDescription: 'Dropped device and the lower half of the screen is unresponsive.',
    priority: 'HIGH',
    status: 'INVOICED',
    sourceChannel: 'WHATSAPP',
    pickupAgent: 'Ravi Pickup',
    technician: 'Mohan Tech',
    deliveryAgent: 'Sara Drop',
    committedAt: '2026-03-23T09:00:00Z',
    expectedCompletionAt: '2026-03-25T09:00:00Z',
    slaDeadlineAt: '2026-03-25T09:00:00Z',
    actualResolutionAt: null,
    tatMinutes: null,
    slaBreached: false,
    breachReason: null,
    invoice: {
      invoiceNumber: 'INV-GSH-20260323-1001',
      paymentStatus: 'PARTIAL',
      gstType: 'CGST_SGST',
      customerGstin: '29ABCDE1234F1Z5',
      billingStateCode: '29',
      placeOfSupply: '29',
      subtotal: 650,
      taxAmount: 117,
      totalAmount: 767,
      cgstAmount: 58.5,
      sgstAmount: 58.5,
      igstAmount: 0,
      amountPaid: 400,
      amountDue: 367,
      refundAmount: 0,
      issuedAt: '2026-03-24T10:00:00Z',
      items: [
        { description: 'Display replacement labour', quantity: 1, unitPrice: 250, taxableValue: 250, gstRate: 9, lineTotal: 250 },
        { description: 'OEM display assembly', quantity: 1, unitPrice: 400, taxableValue: 400, gstRate: 9, lineTotal: 400 }
      ]
    },
    payments: [
      { id: 91, paymentReference: 'PAY-2031', amount: 400, paymentMethod: 'CARD', paymentStatus: 'CAPTURED', refundStatus: 'NOT_APPLICABLE', refundAmount: 0, paidAt: '2026-03-24T11:00:00Z', refundedAt: null }
    ],
    notifications: [
      { channel: 'EMAIL', recipient: 'nisha@example.com', subject: 'Invoice Ready', deliveryStatus: 'SENT', attemptCount: 1, maxAttempts: 3, nextRetryAt: '2026-03-24T10:00:00Z', errorMessage: null, createdAt: '2026-03-24T10:00:00Z' }
    ],
    auditTrail: [
      { entityName: 'Invoice', action: 'CREATE', beforeJson: null, afterJson: '{"amountDue":767}', changedBy: 'Finance Team', changedAt: '2026-03-24T10:00:00Z' },
      { entityName: 'Payment', action: 'CAPTURE', beforeJson: null, afterJson: '{"amount":400}', changedBy: 'Finance Team', changedAt: '2026-03-24T11:00:00Z' }
    ],
    timeline: [
      { fromStatus: null, toStatus: 'REQUEST_CREATED', remarks: 'Request created', changedBy: 'Asha Support', beforeValueJson: null, afterValueJson: '{"status":"REQUEST_CREATED"}', changedAt: '2026-03-23T09:00:00Z' },
      { fromStatus: 'REQUEST_CREATED', toStatus: 'PICKUP_ASSIGNED', remarks: 'Pickup assigned', changedBy: 'Admin', beforeValueJson: '{"pickupAgent":null}', afterValueJson: '{"pickupAgent":"Ravi Pickup"}', changedAt: '2026-03-23T09:15:00Z' },
      { fromStatus: 'DELIVERED', toStatus: 'INVOICED', remarks: 'GST invoice generated', changedBy: 'Finance Team', beforeValueJson: '{"status":"DELIVERED"}', afterValueJson: '{"status":"INVOICED"}', changedAt: '2026-03-24T10:00:00Z' }
    ],
    attachments: [
      { id: 501, attachmentType: 'PICKUP_IMAGE_FRONT', fileName: 'front-view.jpg', contentType: 'image/jpeg', objectKey: '1/front-view.jpg', checksum: 'abc123', signedUrl: 'http://localhost:8080/api/files/access?key=1%2Ffront-view.jpg&expires=1900000000&signature=demo', signedUrlExpiresAt: '2026-03-24T10:15:00Z', uploadedAt: '2026-03-23T11:01:00Z' }
    ],
    createdAt: '2026-03-23T09:00:00Z',
    updatedAt: '2026-03-24T11:00:00Z'
  },
  {
    id: 2,
    requestNumber: 'GSH-20260323-1002',
    tenantCode: 'PARTNER-CARE',
    tenantName: 'Partner Care Electronics',
    loanNumber: 'LN-771245',
    certificateOfInsuranceNumber: 'COI-MUM-3372',
    previousTicketNumber: 'TKT-20260219-982',
    partnerReference: 'PC-99811',
    projectName: 'FG - Mobile All Risk IDFC',
    branchName: 'Andheri East',
    employeeCode: 'EMP-204',
    employeeName: 'Rahul Bansal',
    customerName: 'Omar Khan',
    contactPerson: 'Omar Khan',
    customerPhone: '0502002002',
    alternatePhone: '0502002003',
    whatsappNumber: '0502002002',
    customerGstin: null,
    customerEmail: 'omar@example.com',
    secondaryEmail: null,
    customerAddress: '8 Palm Residency, Andheri',
    landmark: 'Opposite City Mall',
    googleMapLink: 'https://maps.google.com/?q=Andheri+East',
    customerCity: 'Mumbai',
    customerState: 'Maharashtra',
    customerPostalCode: '400059',
    deviceLabel: 'Samsung Galaxy S23',
    deviceCategory: 'MOBILE',
    serialNumber: 'SMS-S23-23-002',
    imeiNumber: '356938035643809',
    imeiValidationStatus: 'QR_EXTRACTED',
    qrCodePayload: 'SN=XYZ;IMEI1=356938035643809',
    issueSummary: 'Battery drains quickly',
    issueDescription: 'Battery health dropped sharply over the last two weeks.',
    priority: 'MEDIUM',
    status: 'OUT_FOR_DELIVERY',
    sourceChannel: 'WEB',
    pickupAgent: 'Ravi Pickup',
    technician: 'Mohan Tech',
    deliveryAgent: 'Sara Drop',
    committedAt: '2026-03-22T08:00:00Z',
    expectedCompletionAt: '2026-03-23T20:00:00Z',
    slaDeadlineAt: '2026-03-23T20:00:00Z',
    actualResolutionAt: null,
    tatMinutes: null,
    slaBreached: true,
    breachReason: 'Awaiting doorstep handoff beyond SLA',
    invoice: null,
    payments: [],
    notifications: [
      { channel: 'EMAIL', recipient: 'ops@partner-care.local', subject: 'SLA Breach Alert', deliveryStatus: 'QUEUED', attemptCount: 0, maxAttempts: 3, nextRetryAt: '2026-03-23T18:05:00Z', errorMessage: null, createdAt: '2026-03-23T18:00:00Z' }
    ],
    auditTrail: [
      { entityName: 'ServiceRequest', action: 'SLA_BREACH', beforeJson: null, afterJson: '{"slaBreached":true}', changedBy: 'SYSTEM', changedAt: '2026-03-23T18:00:00Z' }
    ],
    timeline: [
      { fromStatus: null, toStatus: 'REQUEST_CREATED', remarks: 'Request created', changedBy: 'Portal', beforeValueJson: null, afterValueJson: '{"status":"REQUEST_CREATED"}', changedAt: '2026-03-22T08:00:00Z' },
      { fromStatus: 'DELIVERY_ASSIGNED', toStatus: 'OUT_FOR_DELIVERY', remarks: 'Courier en route', changedBy: 'Sara Drop', beforeValueJson: '{"status":"DELIVERY_ASSIGNED"}', afterValueJson: '{"status":"OUT_FOR_DELIVERY"}', changedAt: '2026-03-23T10:00:00Z' }
    ],
    attachments: [],
    createdAt: '2026-03-22T08:00:00Z',
    updatedAt: '2026-03-23T18:00:00Z'
  }
];
